language: node_js #设置语言
node_js: node

# 缓存node_modules文件夹，节省部署的时间
cache:
  directories:
  - node_modules

# 源码所在分支
branches:
  only:
  - master

# 安装依赖
install:
- npm install hexo-cli -g
- npm install

# 执行的命令
script:
- hexo clean
- hexo generate

# 部署
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TAKEN # Set in travis-ci.org dashboard, marked secure
  keep_history: true
  local_dir: public
  repo: afetmin/afetmin.github.io # 你的GitHub Page仓库地址
  target_branch: master