name: hexo
on:
  push:
    branches:
      - master
env:
  GH_REF: github.com/afetmin/afetmin.github.io
  secretId: ${{ secrets.SECRETID }}
  secretKey: ${{ secrets.SECRETKEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "12.22.12"

      - name: Install and Deploy 
        run: |
          npm install hexo-cli -g
          npm install
          hexo clean
          hexo generate
          hexo d
      - name: Deploy github
        run: |
          cd ./public
          git init
          git config user.name "afetmin"
          git config user.email "kingpenguins@163.com"
          git add .
          git commit -m "GitHub Actions 自动部署"
          git push --force --quiet "https://${{secrets.CI_TOKEN}}@${{env.GH_REF}}" master:master

